version: '2'

services:

  ldap:
    image: h3nrik/apacheds
    ports:
      - 10389:10389
    volumes:
      - /data/ldap:/var/lib/apacheds-2.0.0-M20
    networks:
      - isolated_nw

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - isolated_nw

  sonarqube:
    image: ats-sonarqube-image
    ports:
      - 9000:9000
    volumes:
      - /data/sonarqube:/appl/sonarqube/data
    networks:
      - isolated_nw
    depends_on:
      - ldap
      - mysql

  jenkins:
    image: ats-jenkins-image
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    networks:
      - isolated_nw
    depends_on:
      - ldap
  
  nexus-2:
    image: sonatype/nexus
    ports:
      - 8081:8081
    volumes:
      - /data/nexus-2:/sonatype-work
    networks:
      - isolated_nw
    depends_on:
      - ldap

  nexus-3:
    image: sonatype/nexus3
    ports:
      - 8082:8081
    volumes:
      - /data/nexus-3:/nexus-data
    networks:
      - isolated_nw
    depends_on:
      - ldap

networks:
  isolated_nw:
    external:
      name: isolated_nw