version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: welcome
      key: value
    volumes:
      - /data/wordpress:/var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    volumes:
      - /data/mysql-data:/var/lib/mysql