version: '3.1'

services:

  ldap:
    image: h3nrik/apacheds
    ports:
      - 10389:10389
    networks:
      - ats-ci
    volumes:
      - /data/ldap:/var/lib/apacheds-2.0.0-M20
    deploy:
      replicas: 1
      restart_policy:
        condition:  on-failure
  
  jenkins:
    image: ats-jenkins-image:2.60.3
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    networks:
      - ats-ci
    depends_on:
      - ldap
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      COMMAND_OPTIONS: -master jenkins:8080 -labels docker -executors 2 -mode exclusive
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins-agent:/workspace
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker] 
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8086:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  mysql-pw:
    external: true

networks:
  ats-ci:  