version: "2"

services: 

  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules2:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: welcome

volumes:
  drupal-modules2:
  drupal-profiles:
  drupal-sites:
  drupal-themes: